services:
  - mysql
  - postgresql

addons:
  postgresql: "9.4"

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

env:
  - DB=postgres DB_USER=postgres
  - DB=mysql

before_script:
  - mysql -u root -e 'create database IF NOT EXISTS light_record;'
  - psql -c 'create database light_record;' -U postgres

script: "rake test"
