name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [2.7, '3.0', 3.1]
        gemfile: [ Gemfile, Gemfile.rails-5, Gemfile.rails-6 ]

    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # bundler-cache: true
      - run: |
        bundle install
        bundle exec rake test
